### ISSUE TITLE
Possible to contribute back to CAS?

### ISSUE THREAD

**Issue by mmoayyed** [bliblidotcom/cas-fortress-example#1]
Hi there,

In light of the post here:
http://directory.apache.org/fortress/testimonials.html

I have created an issue to track this here:
https://github.com/apereo/cas/issues/1245

- Would you be interested in the contributing the authN Handler,  etc back to the Apereo CAS server project?
- If you do not have the time, do you mind if I borrowed the code from here and made that contribution on your behalf? (The code is under Apache v2 I see, but I may need to ask you to sign the CAS CLA)

Thanks very much for the excellent guide by the way.

**Comment by yudhik** [comment]
Of course it is possible. I will branch and do the pull request to CAS repository.

**Comment by mmoayyed** [comment]
this is of course done. thanks!!
